- hosts: localhost
  vars:
    artifactory_host: 172.31.0.42
  tasks:
    - name: Install Git
      become: yes
      become_method: sudo
      yum: name=git state=latest

    - name: Clone Pet-Clinic
      git: repo=https://github.com/ytennen/spring-petclinic dest=/devops-course/petclinic/ update=no

    - name: Clone CourseFiles
      git: repo=https://github.com/shimib/devops dest=/devops-course/devops/ update=no

    - name: Install Maven
      get_url: url=http://apache.mivzakim.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz dest=/devops-course/apache-maven-3.3.9-bin.tar.gz mode=0777

    - name: UnArchive
      unarchive: src=/devops-course/apache-maven-3.3.9-bin.tar.gz dest=/devops-course

    - name: set M2_HOME
      lineinfile: dest=/home/ec2-user/.bash_profile regexp="^M2_HOME.*" insertbefore="^PATH=" line="M2_HOME=/home/ec2-user/apache-maven-3.3.9/"
    - name: export M2_HOME
      lineinfile: dest=/home/ec2-user/.bash_profile insertafter="^M2_HOME=" line="export M2_HOME"
    - name: set M2
      lineinfile: dest=/home/ec2-user/.bash_profile insertafter="^M2_HOME=" line="M2=$M2_HOME/bin"
    - name: export M2
      lineinfile: dest=/home/ec2-user/.bash_profile insertafter="^M2=" line="export M2"
    - name: Add M2 to PATH
      lineinfile: dest=/home/ec2-user/.bash_profile insertafter="^PATH=" line="PATH=$PATH:$M2"
    
    - name: Ensure Jenkins Yum repo present
      become: yes
      become_method: sudo
      get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo
           dest=/etc/yum.repos.d/jenkins.repo mode=0644

    - name: update settings.xml
      template: src=/devops-course/devops/settings.xml dest=/devops-course/apache-maven-3.3.9/conf/settings.xml

    - name: Ensure Jenkins GPG key installed
      command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
      become: yes
      become_method: sudo

    - name: Ensure Jenkins installed
      yum: name=jenkins state=present
      become: yes
      become_method: sudo
    - name: Ensure Jenkins is running
      service: name=jenkins state=running enabled=true
      become: yes
      become_method: sudo
